/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.contadini.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Clienti service. Represents a row in the &quot;clienti&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.contadini.servicebuilder.model.impl.ClientiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.contadini.servicebuilder.model.impl.ClientiImpl}.
 * </p>
 *
 * @author leo
 * @see Clienti
 * @see it.contadini.servicebuilder.model.impl.ClientiImpl
 * @see it.contadini.servicebuilder.model.impl.ClientiModelImpl
 * @generated
 */
public interface ClientiModel extends BaseModel<Clienti> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a clienti model instance should use the {@link Clienti} interface instead.
	 */

	/**
	 * Returns the primary key of this clienti.
	 *
	 * @return the primary key of this clienti
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this clienti.
	 *
	 * @param primaryKey the primary key of this clienti
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the clienti ID of this clienti.
	 *
	 * @return the clienti ID of this clienti
	 */
	public long getClientiId();

	/**
	 * Sets the clienti ID of this clienti.
	 *
	 * @param clientiId the clienti ID of this clienti
	 */
	public void setClientiId(long clientiId);

	/**
	 * Returns the nome of this clienti.
	 *
	 * @return the nome of this clienti
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this clienti.
	 *
	 * @param nome the nome of this clienti
	 */
	public void setNome(String nome);

	/**
	 * Returns the cognome of this clienti.
	 *
	 * @return the cognome of this clienti
	 */
	@AutoEscape
	public String getCognome();

	/**
	 * Sets the cognome of this clienti.
	 *
	 * @param cognome the cognome of this clienti
	 */
	public void setCognome(String cognome);

	/**
	 * Returns the email of this clienti.
	 *
	 * @return the email of this clienti
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this clienti.
	 *
	 * @param email the email of this clienti
	 */
	public void setEmail(String email);

	/**
	 * Returns the indirizzo of this clienti.
	 *
	 * @return the indirizzo of this clienti
	 */
	@AutoEscape
	public String getIndirizzo();

	/**
	 * Sets the indirizzo of this clienti.
	 *
	 * @param indirizzo the indirizzo of this clienti
	 */
	public void setIndirizzo(String indirizzo);

	/**
	 * Returns the cap of this clienti.
	 *
	 * @return the cap of this clienti
	 */
	@AutoEscape
	public String getCap();

	/**
	 * Sets the cap of this clienti.
	 *
	 * @param cap the cap of this clienti
	 */
	public void setCap(String cap);

	/**
	 * Returns the telefono of this clienti.
	 *
	 * @return the telefono of this clienti
	 */
	@AutoEscape
	public String getTelefono();

	/**
	 * Sets the telefono of this clienti.
	 *
	 * @param telefono the telefono of this clienti
	 */
	public void setTelefono(String telefono);

	/**
	 * Returns the data compilazione of this clienti.
	 *
	 * @return the data compilazione of this clienti
	 */
	@AutoEscape
	public String getDataCompilazione();

	/**
	 * Sets the data compilazione of this clienti.
	 *
	 * @param dataCompilazione the data compilazione of this clienti
	 */
	public void setDataCompilazione(String dataCompilazione);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Clienti clienti);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Clienti> toCacheModel();

	@Override
	public Clienti toEscapedModel();

	@Override
	public Clienti toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}